### ISSUE TITLE
How does one "Put this tool behind a Wireguard connection?"

### ISSUE THREAD

**Issue by eph-eye-en** [malcolmseyd/natpunch-go#13]
The readme says "I'd recommend putting this tool behind a Wireguard connection with the server as there's no authentication yet." This makes sense, but I'm confused about how to do it.

As I understand it, the server records the IP address of each client and shares that with other clients when requested, allowing them to establish communication between themselves. Wouldn't connecting to the server via Wireguard change the IPs seen by the server to Wireguard specific ones, removing the possibility for a direct P2P connection? Have I misunderstood the instructions/how hole-punching works?

**Comment by malcolmseyd** [comment]
You're totally right, it wouldn't work if you did that. I'll remove the recommendation from the README.
